development:
    clients:
        default:
            database: mongoid_dev
            hosts:
                - mongo:27017

test:
    clients:
        default:
            database: mongoid_dev
            hosts:
                - mongo:27017
