development:
    options:
        raise_not_found_error: false
    clients:
        default:
            database: mongoid_dev
            hosts:
                - mongo:27017

test:
    options:
        raise_not_found_error: false
    clients:
        default:
            database: mongoid_dev
            hosts:
                - mongo:27017
